### ISSUE TITLE
Conflict with CtrlP plugin

### ISSUE THREAD

**Issue by renkam** [Yggdroot/hiPairs#1]
When using hiPairs together with CtrlP plugin there is a conflict after activating CtrlP.
I get error:

Error detected while processing function <SNR>24_HiPairs[114]..<SNR>24_ClearMatch:
line    3:
E803: ID not found: 5

**Comment by Yggdroot** [comment]
Can not reproduce, are you using the latest version? Or could you give more detail?

**Comment by renkam** [comment]
I am using latest version (pulled yesterday).
I am facing this under cygwin vim:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  8 2015 00:46:23)
Included patches: 1-801, 803-808, 810-891

with CtrlP pulled up to commit: 564176f (this is current latest)

Steps to reproduce:
Launch vim, hit Ctrl+P, hit UP arrow key (to higlight different file)
Result: Error is displayed - described in previous post
Expectation: Normal CtrlP behaviour - move highlighting line up

CtrlP config:

" CtrlP plugin
" -- extensions
let g:ctrlp_extensions = ['mixed', 'tag']
" -- pre-fill word at cursor key mapping
nmap <leader>w :CtrlP<CR><C-\>w
" -- mapping for tag in current buffer search
map <Tab> :CtrlPBufTag<CR>
" -- mapping for MRU (Most Recently Used) files
map <CR> :CtrlPMRUFiles<CR>
" -- top dir marker files
let g:ctrlp_root_markers = ['GTAGS', 'tags', '.git', 'includes.mak']
" -- ignore specifica dirs and files
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/].(git|hg|svn)$',
    \ 'file': '\v.(exe|so|dll|o|bin|d|lob|lib|axf)$',
    \ }
" -- result window size limit, but allow for scroll for more results
let g:ctrlp_match_window = 'max:25,results:100'
" -- search from dir mode (this actually should fallback to default as 'w' mode works only with 'r' mode, whitch is not present here)
let g:ctrlp_working_path_mode = 'w'
" -- layzy update especially needed for tag search
let g:ctrlp_lazy_update = 1
" -- by default start in filename mode (toggle with <C-d>)
let g:ctrlp_by_filename = 1

For hiPairs I've changed only colors so config should not be relevant.
If you give me some hints I might try to provide some more details (for example where to put some echos in hiPairs to see the inputs?).

**Comment by Yggdroot** [comment]
Sorry, I still can not reproduce it.

**Comment by renkam** [comment]
Ok, so could you please point me what should I do track the error?
From browsing the plugin code I can see that it tries to delete id of a match and it could not find it (for some reason).
Maybe it would be better to use clearmatches() instead?

**Comment by renkam** [comment]
Ok clearmatches() indeed fixex error, but unfortunately interferences with Mark plugin (MARK by Ingo Karkat) causing all my marks to disappear.

**Comment by Yggdroot** [comment]
To fix this issue is easy, just enclose the code in ClearMatch() with `try...catch`. But I don't know why this happens in logic.

**Comment by renkam** [comment]
Thanks for the fix. This indeed helps.
I've did some tracking about which IDs are added/deleted by hiPairs and it looks like this is a problem with some other plugin which might use clearmatches() or something similar (if I understand those functions correctly).
Anyway thanks for fix.
