### ISSUE TITLE
我在Gitly上看到这个仓库，不错的插件。

### ISSUE THREAD

**Issue by wsdjeg** [Yggdroot/hiPairs#2]
目前我在用`junegunn/rainbow_parentheses.vim`，这两个插件一起用的话不知道是否有问题，我这会不在自己电脑旁边，晚上回去试试。

**Comment by wsdjeg** [comment]
已测试，这两个插件 存在兼容问题;你的这个插件只能在括号下面，加上短横
![2016-01-30 12 46 57](https://cloud.githubusercontent.com/assets/13142418/12693755/a5b24eec-c74f-11e5-9ee5-085a4d9f8357.png)

**Comment by Yggdroot** [comment]
默认就是在下面加个下划线好吧。可以修改任意你想要的颜色。

**Comment by wsdjeg** [comment]
原来是这样呀，我看的介绍里面的图片，谢谢！我试着设置下。

**Comment by wsdjeg** [comment]
![1](https://cloud.githubusercontent.com/assets/13142418/12693831/fc95ad50-c752-11e5-8f09-588050524814.png)
![2](https://cloud.githubusercontent.com/assets/13142418/12693832/fca0ab1a-c752-11e5-802e-447c0e996981.png)
![3](https://cloud.githubusercontent.com/assets/13142418/12693833/fcd32e28-c752-11e5-898c-9d8afed2a1a0.png)
`{` 似乎优点问题

**Comment by Yggdroot** [comment]
没有问题，光标放到括号上，首先会显示匹配的括号。

**Comment by wsdjeg** [comment]
当文件比较长的时候，上下移动光标会有点卡顿。

**Comment by Yggdroot** [comment]
是有点性能问题，目前还没想到好的解决方法。可以把g:hiPairs_timeout和g:hiPairs_insert_timeout值设的小点，缺省值是20。也可以把代码中的`let s_skip=xxx`变成 `let s_skip = ''`，这样基本就没有性能问题了，但是注释里的括号就不会忽略了。

**Comment by wsdjeg** [comment]
我觉得似乎可以参考下 junegunn/rainbow_parentheses.vim ，他这个插件在大文件也不卡顿

**Comment by Yggdroot** [comment]
原理不一样，你可以看看他们的源码。
