### ISSUE TITLE
Takes lot of CPU time when press and hold j/k if the file is large

### ISSUE THREAD

**Issue by ratheesh** [Yggdroot/hiPairs#4]
This is a very good plugin. But if I try to navigate by pressing j/k in a large file, CPU utilization seems on a higher side and the cursor jumps to the right side of command line more often than a normal use case.

It will be nice to reduce CPU utilization and make navigation smoother.

**Comment by Yggdroot** [comment]
Sorry, I don't maintain this plugin any more.

**Comment by ratheesh** [comment]
Thanks for the comment.
Do you know if any other vim plugin which achieves this functionality?

**Comment by Yggdroot** [comment]
https://github.com/vim-scripts/ShowPairs  ?

**Comment by ratheesh** [comment]
@Yggdroot This matches my requirement partially. Thanks for the suggestion.

**Comment by ratheesh** [comment]
Closing this issue as I was able to address this issue by removing `CursorMoved` autocmd.
