### ISSUE TITLE
能指定不检测的字符吗

### ISSUE THREAD

**Issue by likelxl** [Yggdroot/hiPairs#5]
比如->,=>,>=,<=

**Comment by Yggdroot** [comment]
不能。

**Comment by likelxl** [comment]
哦,还会更新加进去吗?

**Comment by Yggdroot** [comment]
不打算维护这个插件了，这个插件有性能问题。

**Comment by likelxl** [comment]
好吧.我还不会写,我只会用.能推荐插件开发的文档吗?

**Comment by Yggdroot** [comment]
首先，需要了解一下vim脚本的加载流程，例如：`h syntax-loading`，`h rtp`，`h autoload`，`h after`。vimL本身语法挺简单的，看看自带的帮助文档应该就可以熟悉了（`h eval`)，关键还是要用才行，比如自己实现个什么小功能。
我觉得能利用好自带的帮助文档就够了，自带帮助文档我从头到尾看了不下2遍。
推荐两个链接：虽然我都没怎么看过。（因为当我遇到他们时，发现他们讲的内容我都会了）
https://github.com/wsdjeg/vim-galore-zh_cn
http://learnvimscriptthehardway.stevelosh.com/

**Comment by likelxl** [comment]
谢谢
