### ISSUE TITLE
[question] why g:hiPairs_hl_matchPair?

### ISSUE THREAD

**Issue by jlesquembre** [Yggdroot/hiPairs#7]
thanks for writing this plugin, it was exactly the functionality I was looking for :)

I have one question, why do you recommend to use `g:hiPairs_hl_matchPair` instead of just using `hiPairs_matchPair` directly? Do you think it can problematic to use `hiPairs_matchPair` directly in my init.vim?

**Comment by Yggdroot** [comment]
There is no difference.

**Comment by jlesquembre** [comment]
Thanks for clarifying!
